# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/110HekxkF2ys04GQUyuSeAErikappsBrC
"""

import os,sys
from google.colab import drive

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

drive.mount('/content/drive') 
os.chdir("/content/drive/MyDrive/Colab Notebooks/")

dataset = pd.read_csv("GasMlr.csv")

dataset

x = dataset.drop('TAT', axis=1)

#x=dataset.iloc[2:,6].values.reshape(-1,1)

x

#y=dataset.iloc[2:,6].values.reshape(-1,1)

y = dataset['TAT']

y

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=1/3,random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
LinearRegression()

regressor.score(x_test,y_test)

y_pred = regressor.predict(x_test)

d = {'y_pred': y_pred, 'y_test': y_test}

#regressor.predict([[4.5878,1018.7,83.675,3.5758,23.979,1086.2,549.83,134.67,11.898,0.32663]])

y_pred

from matplotlib.font_manager import findSystemFonts
plt.title('Actual Vs Predicted')
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.scatter(y_test,y_pred)
plt.figure(figsize=(15,10))

pred_y_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_pred,'Difference':y_test-y_pred})
print(pred_y_df)